server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
      repositories:
        enabled: false
  jwt:
    secret: ${JWT_SECRET}
  default:
    admin_id: imMaster@naver.com
    admin_pwd: 1234
  thymeleaf:
    suffix: .html
    prefix: classpath:templates/
    cache: false
    check-template-location: true
    mode: HTML
  mvc:
    static-path-pattern: "/static/**"

  aes:
    secret: ${AES_KEY}
  logging:
    config: classpath:logback-spring-dev.xml
  springdoc:
    default-produces-media-type: application/json;charset=UTF-8
    default-consumes-media-type: application/json;charset=UTF-8
    cache:
      disabled: true
    packages-to-scan: org.book.commerce.bookcommerce.controller
    api-docs:
      path: /swagger-ui
  datasource:
    url: jdbc:mysql://localhost:3306/whateverWithMe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: l36475068@gmail.com
    password: ${SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

