version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: heeju
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"

  redis:
    image: redis
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"