server:
  port: 8013
spring:
  cache:
    type: redis
  application:
    name: application-product
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
logging:
  level:
    org.springframework.cloud.config: DEBUG
