server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linxizhu1209/config-repo
          default-label: master
          cloneOnStart: true
          basedir: /path/to/local/git/cache
        bootstrap: true
encrypt:
  key: ${ENCRYPT_KEY}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true