name: CI/CD for discovery-server

on:
  push:
    branches:
      - dev
    paths:
      - discovery-server/**
  pull_request:
    branches:
      - dev
    paths:
      - discovery-server/**
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER_NAME: ${{ secrets.DB_USER_NAME }}
      DB_USER_PWD: ${{ secrets.DB_USER_PWD }}
      CONFIG_GIT_URL: ${{ secrets.CONFIG_GIT_URL }}
      ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -p discovery-server


      - name: Test with Gradle
        run: ./gradlew test -p discovery-server

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/discovery-server:latest -f ./discovery-server/Dockerfile ./discovery-server


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/discovery-server:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull discovery-server
          docker-compose up -d discovery-server
        working-directory: ./