name: CI/CD for Product Service

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER_NAME: ${{ secrets.DB_USER_NAME }}
      DB_USER_PWD: ${{ secrets.DB_USER_PWD }}
      CONFIG_GIT_URL: ${{ secrets.CONFIG_GIT_URL }}
      ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Load environment variables from .env file
#        run: |
#          echo "Loading environment variables from .env file"
#          set -o allexport
#          source .env
#          set +o allexport

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -p product-service

      - name: Test with Gradle
        run: ./gradlew test -p product-service

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest -f ./product-service/Dockerfile ./product-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose pull product-server
          docker-compose up -d product-server
        working-directory: ./